name: Release
on:
  workflow_dispatch:
    inputs:
      stage:
        description: Stage
        type: choice
        required: true
        options: 
        - preview
        - production
      versionName:
        description: 'Version name'
        type: string
        required: true
      bumpVersionCode:
        description: 'Bump version code'
        type: boolean
        required: true
        default: true

jobs:
  updateVersion:
    runs-on: self-hosted
    if: ${{ inputs.bumpVersionCode }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: '${{ inputs.stage }}/${{ inputs.versionName }}'
      - name: Setup
        uses: ./.github/actions/setup
      - name: Update version name and bump version code
        run: bundle exec fastlane updateVersion version_name:${{ inputs.versionName }}

  release:
    runs-on: self-hosted
    needs: updateVersion
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: '${{ inputs.stage }}/${{ inputs.versionName }}'
      - name: Setup
        uses: ./.github/actions/setup
      - name: Deploy key store
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          KEYSTORE_PATH=$RUNNER_TEMP/keystore.jks
          echo -n "$KEYSTORE_BASE64" | base64 --decode --output $KEYSTORE_PATH
          echo "KEYSTORE_PATH=$KEYSTORE_PATH" >> $GITHUB_ENV
      - name: Deploy fastlane API key
        env:
          FASTLANE_API_KEY: ${{ secrets.FASTLANE_API_KEY }}
        run: |
          FASTLANE_API_KEY_PATH=$RUNNER_TEMP/fastlane_api_key.json
          echo -n "$FASTLANE_API_KEY" > $FASTLANE_API_KEY_PATH
          echo "FASTLANE_API_KEY_PATH=$FASTLANE_API_KEY_PATH" >> $GITHUB_ENV
      - name: Build release and submit to Google Play Store
        env:
          KEYSTORE_PATH: ${{ env.KEYSTORE_PATH }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          FASTLANE_API_KEY_PATH: ${{ env.FASTLANE_API_KEY_PATH }}
          UPLOAD_KEY_PASSWORD: ${{ secrets.UPLOAD_KEY_PASSWORD }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: digitalservice
          SENTRY_PROJECT: useid-preview-android
        run: bundle exec fastlane release stage:${{ inputs.stage }}
